#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

GLSADIR="${repository_path}"/metadata/glsa
ebegin "Updating GLSAs"
if [[ -e ${GLSADIR} ]]; then
	su -c "git -C '${GLSADIR}' pull -q --ff-only" "${SYNC_USER:=root}"
else
	su -c "git clone -q https://anongit.gentoo.org/git/data/glsa.git '${GLSADIR}'" "${SYNC_USER:=root}"
fi
eend "$?"
